# Generated by Django 3.1.2 on 2020-10-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201019_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, default='', max_length=100, verbose_name='Estado')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.DeleteModel(
            name='Lugar',
        ),
    ]
